apiVersion: v1
kind: Pod
metadata:
  # pod名
  name: sample-php-pod
  labels:
    app: http-app
spec:
  containers:
    # Dockerコンテナ名
    - name: php-container
      # 利用するDockerイメージ
      image: php:7.0-apache
      # コンテナ内のport
      ports:
        - name: http-port
          containerPort: 80
      # mountするディレクトリ：コンテナ側の設定
      volumeMounts:
        - name: documentroot
          mountPath: /var/www/html
  # mountするディレクトリ：ホストOS側の設定
  volumes:
    - name: documentroot
      hostPath:
        path: /home/username/containers/web/html